name: Lint
on:
  push:
      branches: [main]

jobs:
  build:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v3

        - name: Set up go
          uses: actions/setup-go@v3
          with:
            go-version: 1.18

        - name: Build
          run: make build

        - name: Test
          run: make test
